export enum ErrorCode {
  // Validation
  INVALID_AMOUNT = "INVALID_AMOUNT",
  MISSING_IDEMPOTENCY_KEY = "MISSING_IDEMPOTENCY_KEY",
  INVALID_WALLET_ID = "INVALID_WALLET_ID",
  INVALID_CURRENCY = "INVALID_CURRENCY",
  INVALID_USERID = "INVALID_USERID",
 

  // Business
  INSUFFICIENT_FUNDS = "INSUFFICIENT_FUNDS",
  WALLET_LOCKED = "WALLET_LOCKED",
  WALLET_CLOSED = "WALLET_CLOSED",
  MAX_LIMIT_EXCEEDED = "MAX_LIMIT_EXCEEDED",

  // Concurrency
  VERSION_CONFLICT = "VERSION_CONFLICT",
  IDEMPOTENCY_CONFLICT = "IDEMPOTENCY_CONFLICT",

  // System
  DATABASE_ERROR = "DATABASE_ERROR",
  REDIS_ERROR = "REDIS_ERROR",
  INTERNAL_ERROR = "INTERNAL_ERROR"
}